In [50]:
import pandas as pd
data = pd.read_csv("/Users/csb/Desktop/Project/넙치 머신러닝/0_양식어류 질병예측_221207/20-21-22-23 통합본 Raw 복사본.csv")

In [51]:
from pycaret.classification import *
from sklearn.model_selection import LeaveOneOut

In [52]:
data

,일순환량,사료종류,사료급이량,일평균폐사,백신접종여부,수온,DO,pH,ATP,세균수,...,Wsr6,Wsi2,Wsi3-1,Wsi3-2,Whr7,Whi3,Whi6-1,Whi6-2,Whi6-3,결과
0,20.0,EP,0.0075,30.0,Ⅹ,12.44,7.5,6.97,146.0,4400.0,...,0,8,4,NaN,0,0,0,0,0,주의
1,20.0,EP,0.0075,30.0,Ⅹ,12.44,7.5,6.97,146.0,4400.0,...,0,4,0,NaN,0,0,8,0,0,주의
2,20.0,EP,0.0075,30.0,Ⅹ,12.44,7.5,6.97,146.0,4400.0,...,0,8,0,NaN,0,0,8,0,8,질병
3,20.0,EP,0.0075,30.0,Ⅹ,12.44,7.5,6.97,146.0,4400.0,...,0,4,0,NaN,0,8,0,0,4,주의
4,20.0,EP,0.0075,30.0,Ⅹ,12.44,7.5,6.97,146.0,4400.0,...,0,0,0,NaN,0,8,4,0,0,주의
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,NaN,NaN,NaN,NaN,NaN,23.30,NaN,NaN,NaN,NaN,...,0,8,0,0.0,0,4,0,0,0,주의
1267,NaN,NaN,NaN,NaN,NaN,23.30,NaN,NaN,NaN,NaN,...,0,8,4,0.0,0,4,0,0,0,질병
1268,NaN,NaN,NaN,NaN,NaN,23.30,NaN,NaN,NaN,NaN,...,0,8,0,0.0,0,4,0,0,0,주의
1269,NaN,NaN,NaN,NaN,NaN,23.30,NaN,NaN,NaN,NaN,...,0,8,0,0.0,0,4,0,0,0,질병
1270,NaN,NaN,NaN,NaN,NaN,23.30,NaN,NaN,NaN,NaN,...,0,12,4,0.0,0,4,0,0,0,질병

In [47]:
#data = data[['수온', 'Condition factor', 'ALP', 'T P', 'Wgp2', 'Wgi3', 'Whkp2', 'Whki2-1', 'Wlr1', 'Wlr2-1', 'Wsi2', 'Whi6-1','결과']]
#data = data[ ['사료급이량', '어체중(g)', 'Condition factor', '임상증상유무', 'T P', 'Wgp2', 'Whkr7', 'Whkp2', 'Whki2-1', 'Wlr1', 'Wlr2-1', 'Wsi2','결과']]
#data = data[['사료급이량','백신접종여부', 'DO', '임상증상유무', '기생충유무', 'BUN', 'CREA', 'GLU', 'Whkr7', 'Whkp2', 'Whki2-1', 'Wlr2-1', 'Wsi2','결과']]
#data = data[['사료급이량', '어체중(g)', 'Condition factor', '임상증상유무', 'BUN', 'T P', 'CHOL', 'ALB', 'Wgp2', 'Whkr7', 'Whkp2', 'Whki2-1', 'Wlr1', 'Wlr2-1', 'Wsi2','결과']]
#data = data[['사료급이량', 'DO', '어체중(g)', 'Condition factor', '임상증상유무', 'ALP', 'BUN', 'GLU', 'T P', 'CHOL', 'ALB', 'Wgp2', 'Whkr7', 'Whkp2', 'Whki2-1', 'Wlr1', 'Wlr2-1', 'Wsi2','결과']]
#data = data[['수온', 'Condition factor', 'ALP', 'T P', 'Wgp2', 'Wgi3', 'Whkp2', 'Whki2-1', 'Wlr1', 'Wlr2-1', 'Wsi2', 'Whi6-1','결과']]

data

,사료급이량,DO,어체중(g),Condition factor,임상증상유무,ALP,BUN,GLU,T P,CHOL,ALB,Wgp2,Whkr7,Whkp2,Whki2-1,Wlr1,Wlr2-1,Wsi2,결과
0,0.0075,7.5,528.8,1.828,0,79,1.9,16,5.7,252,1.6,0,4,0,0,0,0,8,1
1,0.0075,7.5,515.4,2.348,0,60,2.2,17,5.4,176,1.7,0,0,8,0,4,0,4,1
2,0.0075,7.5,432.3,1.634,1,95,1.9,14,4.7,275,1.3,0,0,0,8,4,0,8,2
3,0.0075,7.5,573.4,1.906,0,77,2.4,11,5.7,232,1.6,4,0,0,8,4,0,4,1
4,0.0075,7.5,660.8,2.055,0,59,2.2,18,5.9,182,1.7,4,0,4,4,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,0.0597,8.0,376.0,1.900,0,68,7.7,3,3.7,64,0.8,0,0,12,0,4,8,8,1
1267,0.0597,8.0,376.0,1.900,0,36,9.5,3,2.4,59,0.4,0,0,12,4,8,12,8,2
1268,0.0597,8.0,376.0,1.900,0,78,5.5,2,3.5,115,0.6,0,0,12,0,8,4,8,1
1269,0.0597,8.0,376.0,1.900,0,45,13.9,3,3.2,58,0.6,0,4,12,0,8,12,8,2
1270,0.0597,8.0,376.0,1.900,0,36,9.3,3,2.9,72,0.1,0,0,12,0,12,4,12,2

In [ ]:
loocv = LeaveOneOut()

In [53]:
s = setup(data, target = '결과', session_id = 123,fix_imbalance = False, train_size=0.9)
#fold_strategy=loocv,

In [54]:
best = compare_models()

In [55]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…